version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: fridge-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fridge
    ports:
      - "5432:5432"
    volumes:
      - fridge_data:/var/lib/postgresql/data
    networks:
      - fridge-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: fridge-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - fridge-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: fridge-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - fridge-net

volumes:
  fridge_data:

networks:
  fridge-net:
