version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: fridge-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fridge
    ports:
      - "5432:5432"
    volumes:
      - fridge_data:/var/lib/postgresql/data
    networks:
      - fridge-net

volumes:
  fridge_data:

networks:
  fridge-net:
