spring:
  application:
    name: fridge

  datasource:
    url: jdbc:postgresql://localhost:5432/fridge
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: mySuperSecureJwtSecretKeyThatIsAtLeast32BytesLong!!
  expirationMs: 2592000000 # 30 days (600h)